version: '3'

services:

  mysqlDB:
    image: mysql:5.7.27
    restart: always
    ports:
      - "3307:3307"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init-dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456789*
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456789*
      - MYSQL_DB=test
    container_name: mysqlDB

volumes:
  db-data:
