"""empty message

Revision ID: cbf120c3f325
Revises: 6950da323f3c
Create Date: 2019-10-29 19:16:00.554695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbf120c3f325'
down_revision = '6950da323f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantName', sa.String(length=50), nullable=False),
    sa.Column('plantTemperature', sa.Integer(), nullable=False),
    sa.Column('plantLux', sa.Integer(), nullable=False),
    sa.Column('soilMoisture', sa.Integer(), nullable=False),
    sa.Column('plantDetails', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_table('plant')
    # ### end Alembic commands ###
