"""empty message

Revision ID: 0add7aac897d
Revises: 
Create Date: 2019-11-11 18:46:54.489157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0add7aac897d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('plant')
    op.add_column('configs', sa.Column('param1', sa.String(length=50), nullable=False))
    op.add_column('configs', sa.Column('param2', sa.String(length=50), nullable=False))
    op.add_column('configs', sa.Column('param3', sa.String(length=50), nullable=False))
    op.drop_column('configs', 'idPlant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('idPlant', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('configs', 'param3')
    op.drop_column('configs', 'param2')
    op.drop_column('configs', 'param1')
    op.create_table('plant',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('plantType', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('plantName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('plantTemperature', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('plantLux', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('soilMoisture', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('plantDetails', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('plants')
    # ### end Alembic commands ###
