"""empty message

Revision ID: 728babb5cd54
Revises: c77cf7c2f3c8
Create Date: 2019-11-13 19:21:42.483985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '728babb5cd54'
down_revision = 'c77cf7c2f3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('lux', sa.Integer(), nullable=False))
    op.add_column('sensor', sa.Column('moisture', sa.Integer(), nullable=False))
    op.add_column('sensor', sa.Column('temperature', sa.Integer(), nullable=False))
    op.drop_column('sensor', 'soilMoisture')
    op.drop_column('sensor', 'plantLux')
    op.drop_column('sensor', 'plantTemperature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('plantTemperature', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('sensor', sa.Column('plantLux', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('sensor', sa.Column('soilMoisture', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('sensor', 'temperature')
    op.drop_column('sensor', 'moisture')
    op.drop_column('sensor', 'lux')
    # ### end Alembic commands ###
