"""empty message

Revision ID: 8e02c1140792
Revises: 
Create Date: 2019-11-13 19:11:28.181413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e02c1140792'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('plantTemperature', sa.Integer(), nullable=False),
    sa.Column('soilMoisture', sa.Integer(), nullable=False),
    sa.Column('plantLux', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plantId'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    op.drop_table('plant')
    # ### end Alembic commands ###
