"""empty message

Revision ID: 9b7b47616684
Revises: 0add7aac897d
Create Date: 2019-11-11 19:05:39.698813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b7b47616684'
down_revision = '0add7aac897d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configs', 'param3')
    op.drop_column('configs', 'param2')
    op.drop_column('configs', 'param1')
    op.add_column('plants', sa.Column('plantLux', sa.Integer(), nullable=False))
    op.add_column('plants', sa.Column('plantTemperature', sa.Integer(), nullable=False))
    op.add_column('plants', sa.Column('soilMoisture', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'soilMoisture')
    op.drop_column('plants', 'plantTemperature')
    op.drop_column('plants', 'plantLux')
    op.add_column('configs', sa.Column('param1', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('configs', sa.Column('param2', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('configs', sa.Column('param3', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
