"""empty message

Revision ID: be8a9eadcdb2
Revises: 
Create Date: 2019-11-17 01:59:55.882198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8a9eadcdb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('moisture', sa.Integer(), nullable=False),
    sa.Column('lux', sa.Integer(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('moisture', sa.Integer(), nullable=False),
    sa.Column('lux', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor')
    op.drop_table('plant')
    # ### end Alembic commands ###
