"""empty message

Revision ID: eddddf0d3e73
Revises: 9b7b47616684
Create Date: 2019-11-11 21:06:20.257689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eddddf0d3e73'
down_revision = '9b7b47616684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('plantTemperature', sa.Integer(), nullable=False),
    sa.Column('soilMoisture', sa.Integer(), nullable=False),
    sa.Column('plantLux', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plantId'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('plants')
    op.drop_table('configs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('plants',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('config_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('plantLux', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('plantTemperature', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('soilMoisture', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], name='plants_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('config')
    op.drop_table('plant')
    # ### end Alembic commands ###
